CREATE TABLE WISHLIST
(
  ID SERIAL primary key,
  USER_ID SERIAL not null,
  COMPONENT_ID SERIAL not null,
  CREATION_DATE TIMESTAMP default current_timestamp
);

ALTER TABLE WISHLIST
    ADD FOREIGN KEY (USER_ID) references USERS (ID);

ALTER TABLE WISHLIST
    ADD FOREIGN KEY (COMPONENT_ID) references COMPONENTS (ID);
