name: Purge artifacts

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
  
    steps:
          - uses: kolpav/purge-artifacts-action@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              expire-in: 10 minutes
