name: Push build to production

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: |
          mvn package -P ui -pl pios-app-ui -q
          mvn package -q checkstyle:check

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "./pios-app-service/target/pios-app-service-*.jar"

      - name: Prepare jar
        run: |
          mkdir temp
          mv ./pios-app-service/target/pios-app-service-*.jar temp

      - name: Deploy to production
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-Dzvc -i"
          SOURCE: "temp/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ format('/home/{0}/app', secrets.REMOTE_USER) }}
